---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

platforms:
  - name: ubuntu-14.04
    attributes:
      bind9:
        loglocation: '/var/log/named/'
  - name: debian-8.3
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[bind9-ng::install_bind]
      - recipe[bind9-ng::config]
    attributes:
      bind9:
        id:
          noview: {}
